### ISSUE TITLE
Le bot ne move pas dans le chan

### ISSUE THREAD

**Issue by BrouxeeS** [GLedoussal/discord-vocaltext#1]
Salut, j'ai voulu tester le bot, tout fonctionne sauf le move, quand je rejoins un salon vocal il créé une notification mais ne déplace pas l'utilisateur dans le salon textuel associé, niveau permissions il a tout... 
Si jamais tu as le temps, je suis preneur pour avoir quelques explications ! :)

**Comment by khalen56** [comment]
Hello,

Je vais voir ce qui se passe quand j'aurais un moment. Ça me paraît bizarre
qu'il ne fonctionne pas. Essaye de voir si tu es bien à jour sur le dernier
commit (j'ai ajouté le log des arrivées / sorties mais ça se désactive avec
la conf). J'avais fait une erreur, ça ne fonctionnait pas avec les channels
qui avaient plusieurs espaces dans le nom.

**Comment by BrouxeeS** [comment]
Salut,

Donc j'ai bien le dernier commit étant donné que j'ai les logs des arrivées / sorties. Je continue mes tests de mon côté je te tiens au jus, si ça se trouve c'est moi qui manipule pas bien le bot ?

Edit: J'ai réussi à gérer le fait (avec les permissions) que seul le salon textuel associé au vocal soit affiché pour l'user, finalement le problème c'est que que ça met pas l'user dans le salon à proprement parler il doit cliquer sur le salon textuel sinon un message d'erreur s'affiche. (cf le screen)

![image](https://cloud.githubusercontent.com/assets/15182452/21914470/d6fd2796-d933-11e6-808d-bc32de6569fc.png)

**Comment by khalen56** [comment]
Il n'y a pas grand chose à faire à part lui donner accès à tous les chans
et les droits de gérer les groupes. Quels sont les noms de tes channels ?
(vocaux et textuels)

**Comment by BrouxeeS** [comment]
J'avais fais un édit sur mon commentaire précédent je te le remet ici étant donné que tu réponds via mail et que ça s'actualise pas ! :)
>>>>>
J'ai réussi à gérer le fait (avec les permissions) que seul le salon textuel associé au vocal soit affiché pour l'user, finalement le problème c'est que que ça met pas l'user dans le salon à proprement parler il doit cliquer sur le salon textuel sinon un message d'erreur s'affiche. (cf le screen)

![image](https://cloud.githubusercontent.com/assets/15182452/21914470/d6fd2796-d933-11e6-808d-bc32de6569fc.png)

**Comment by khalen56** [comment]
Oh, oui je vois. Malheureusement c'est une limitation de Discord. Mon petit
script fournit un petit contournement au manque de channel textuel pour les
gens d'un channel vocal mais ne peut en aucun cas choisir le salon actif
d'un utilisateur. Je ne peux rien faire :(

Le ven. 13 janv. 2017 17:41, BrouxeeS <notifications@github.com> a écrit :

J'avais fais un édit sur mon commentaire précédent je te le remet ici étant
donné que tu réponds via mail et que ça s'actualise pas ! :)

J'ai réussi à gérer le fait (avec les permissions) que seul le salon
textuel associé au vocal soit affiché pour l'user, finalement le problème
c'est que que ça met pas l'user dans le salon à proprement parler il doit
cliquer sur le salon textuel sinon un message d'erreur s'affiche. (cf le
screen)

[image: image]
<https://cloud.githubusercontent.com/assets/15182452/21914470/d6fd2796-d933-11e6-808d-bc32de6569fc.png>

—
You are receiving this because you commented.


Reply to this email directly, view it on GitHub
<https://github.com/GLedoussal/discord-vocaltext/issues/1#issuecomment-272484172>,
or mute the thread

**Comment by BrouxeeS** [comment]
Merci pour la réponse, c'est quand même ce que je recherchais ! Ça me permet déjà de limiter les accès aux autres salons textuels pour éviter le flood monstrueux !
